### ISSUE TITLE
مهندس ای کاش فورک میکردی

### ISSUE THREAD

**Issue by Bardiafa** [yebekhe/yebekhe#2]
سلام مهندس ، ممنون از تمام زحماتت برای رپو های خفنت

اتفاقی چشمم خورد به پروفایلت ، ای کاش ریدمی رو که کپی کردی یه استار یا فورک میکردی 😊

(شوخی کردما ، اینجا گیت هابه یعنی اوپن سورس بودن ، نوش جونت)

**Comment by yebekhe** [comment]
ممنون 
من فکر کردم رفرنس جای دیگه یا منبعی غیر از اکانت شماست چون لایسنس هم نخورده بود 
پوزش بابت این مورد 
ریپو استار شد

**Comment by Bardiafa** [comment]
دم شما گرم
